### PR TITLE
Whitelist contract

### PR DESCRIPTION
**Pull request by InfiniteStyles**

### CODE REVIEW

**Comment by InfiniteStyles** [comment]
Not really sure what's up with Travis CI, `npx truffle test` (using Truffle 4) passes for me locally in a non-deterministic manner. So, it's likely that.

**Comment by InfiniteStyles** [comment]
No, although that seems like a good idea. And I will try to do that, after I finish working on the DutchX (as that needs to be launched).

**Comment by InfiniteStyles** [comment]
Updated the pull request. It should be ready to be merged.

**Comment by cag** [comment]
Closing due to a change in project requirements.

**Pull request closed without merging**
